#
# Copyright 2021-2023 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

replicaCount: 1

image:
  # Check https://hub.docker.com/u/softwareradiosystems for available images
  repository: ninjab3s/srsran-5g-gnb
  pullPolicy: IfNotPresent
  tag: "digi-cat-7"

imagePullSecrets: []
#  - name: regcred

nameOverride: "srsran-project-cudu"
fullnameOverride: "srsran-project-cudu-chart"

serviceAccount:
  create: true
  annotations: {}
  name: "srsadmin-gnb"

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    add: ["SYS_NICE", "NET_ADMIN"]
  privileged: true
  hostNetwork: true
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 12
    memory: 16Gi
    hugepages-1Gi: 2Gi
    # intel.com/intel_sriov_dpdk: 1
  requests:
    cpu: 12
    memory: 16Gi
    hugepages-1Gi: 2Gi
    # intel.com/intel_sriov_dpdk: 1

nodeSelector: {}
  # kubernetes.io/hostname: node1

tolerations: {}
  # - key: "purpose"
  #   value: "manual-testing"
  #   operator: "Equal"
  #   effect: "NoSchedule"

affinity: {}

debugging:
  enabled: true
  hostPath: "/mnt/srs"
  containerPath: "/tmp"

config:
  # gnb_id: 2

  # amf:
  #   addr: open5gs-amf-ngap.open5gs.svc.cluster.local                    # The address or hostname of the AMF.
  #   bind_addr: 10.122.141.10                                            # A local IP that the gNB binds to for traffic from the AMF.

  # slicing:
  #   - sst: 1
  #     sd: 1

  # ru_ofh:
  #   t1a_max_cp_dl: 420                                              # Maximum T1a on Control-Plane for Downlink in microseconds.
  #   t1a_min_cp_dl: 250                                              # Minimum T1a on Control-Plane for Downlink in microseconds.
  #   t1a_max_cp_ul: 420                                              # Maximum T1a on Control-Plane for Uplink in microseconds.
  #   t1a_min_cp_ul: 250                                              # Minimum T1a on Control-Plane for Uplink in microseconds.
  #   t1a_max_up: 196                                                 # Maximum T1a on User-Plane in microseconds.
  #   t1a_min_up: 80                                                  # Minimum T1a on User-Plane in microseconds.
  #   ta4_max: 500                                                    # Maximum Ta4 on User-Plane in microseconds.
  #   ta4_min: 25                                                     # Minimum Ta4 on User-Plane in microseconds.
  #   is_prach_cp_enabled: true                                       # Configures if Control-Plane messages should be used to receive PRACH messages.
  #   ignore_ecpri_payload_size: true                                 # Configures if eCPRI payload size field should be ignored by the eCPRI packet decoder.
  #   compr_method_ul: bfp                                            # Uplink compression method.
  #   compr_bitwidth_ul: 9                                            # Uplink IQ samples bitwidth after compression.
  #   compr_method_dl: bfp                                            # Downlink compression method.
  #   compr_bitwidth_dl: 9                                            # Downlink IQ samples bitwidth after compression.
  #   compr_method_prach: bfp                                         # PRACH compression method.
  #   compr_bitwidth_prach: 9                                         # PRACH IQ samples bitwidth after compression.
  #   enable_ul_static_compr_hdr: false                               # Configures if the compression header is present for uplink User-Plane messages (false) or not present (true).
  #   enable_dl_static_compr_hdr: false                               # Configures if the compression header is present for downlink User-Plane messages (false) or not present (true).
  #   iq_scaling: 1.0                                                 # IQ samples scaling factor applied before compression, should be a positive value smaller than 10.
  #   cells:
  #     - network_interface: eno12409                             # Ethernet interface name used to communicate with the RU.
  #       ru_mac_addr: 6C:AD:AD:00:0C:5E                              # RU MAC address.
  #       du_mac_addr: b4:83:51:01:a5:55                              # DU MAC address.
  #       vlan_tag_cp: 805                                              # VLAN tag value for C-Plane.
  #       vlan_tag_up: 805                                              # VLAN tag value for U-Plane.
  #       prach_port_id: [4, 5, 6, 7]                                 # PRACH eAxC port values.
  #       dl_port_id: [0, 1]                                          # Downlink eAxC port values.
  #       ul_port_id: [0, 1, 2, 3]                                    # Uplink eAxC port values.

  # cell_cfg:
  #   dl_arfcn: 649980 # 3749.7MHz                                               # ARFCN of the downlink carrier (center frequency). 
  #   band: 78                                                        # The NR band.
  #   channel_bandwidth_MHz: 100                                       # Bandwith in MHz. Number of PRBs will be automatically derived.
  #   common_scs: 30                                                  # Subcarrier spacing in kHz used for data.
  #   plmn: "00101"                                                   # PLMN broadcasted by the gNB.
  #   tac: 1                                                          # Tracking area code (needs to match the core configuration).
  #   pci: 136                                                          # Physical cell ID.
  #   nof_antennas_dl: 2                                              # Number of transmission antennas.
  #   nof_antennas_ul: 2                                              # Number of reception antennas.
  #   prach:
  #     prach_config_index: 159                                       # PRACH configuration index.
  #     prach_root_sequence_index: 1                                  # PRACH root sequence index.
  #     zero_correlation_zone: 0                                      # Zero correlation zone.
  #     prach_frequency_start: 12                                     # Offset in PRBs of lowest PRACH transmission occasion in frequency domain respective to PRB 0.
  #   pdsch:
  #     mcs_table: qam256

  # log:
  #   filename: /tmp/gnb.log                                          # Path of the log file.
  #   all_level: info
  #   ofh_level: warning                                                 # Logging level applied to all layers.

  # pcap:
  #   mac_enable: false                                               # Set to true to enable MAC-layer PCAPs.
  #   mac_filename: /tmp/gnb_mac.pcap                                 # Path where the MAC PCAP is stored.
  #   ngap_enable: false                                              # Set to true to enable NGAP PCAPs.
  #   ngap_filename: /tmp/gnb_ngap.pcap                               # Path where the NGAP PCAP is stored.

  # metrics:
  #   autostart_stdout_metrics: true                                  # Enable reporting metrics in stdout
  #   enable_json_metrics: true                                       # Enable reporting metrics in JSON format
  #   addr: metrics-srsran-metrics-server.srsran                      # Metrics-server IP/Hostname
  #   # addr: 10.43.244.242                                             # Metrics-server IP/Hostname
  #   port: 55555                                                     # Metrics-server Port

  # test_mode:
  #   test_ue:
  #     rnti: 0x0
  #     ri: 2
  #     cqi: 15
  #     nof_ues: 1
  #     pusch_active: true
  #     pdsch_active: true
  
  gnb_id: 2

  amf:
    addr: 10.122.221.60                                                  # The address or hostname of the AMF.
  #  addr: 10.122.221.56
    n2_bind_addr: 10.122.221.52                                          # A local IP that the gNB binds to for traffic from the AMF.
    n3_bind_addr: 10.122.222.52
    #n3_ext_addr: 10.122.222.52

  ru_ofh:
    t1a_max_cp_dl: 420                                              # Maximum T1a on Control-Plane for Downlink in microseconds.
    t1a_min_cp_dl: 250                                              # Minimum T1a on Control-Plane for Downlink in microseconds.
    t1a_max_cp_ul: 420                                              # Maximum T1a on Control-Plane for Uplink in microseconds.
    t1a_min_cp_ul: 250                                              # Minimum T1a on Control-Plane for Uplink in microseconds.
    t1a_max_up: 196                                                 # Maximum T1a on User-Plane in microseconds.
    t1a_min_up: 80                                                  # Minimum T1a on User-Plane in microseconds.
    ta4_max: 500                                                    # Maximum Ta4 on User-Plane in microseconds.
    ta4_min: 25                                                     # Minimum Ta4 on User-Plane in microseconds.
    is_prach_cp_enabled: true                                       # Configures if Control-Plane messages should be used to receive PRACH messages.
    ignore_ecpri_payload_size: true                                 # Configures if eCPRI payload size field should be ignored by the eCPRI packet decoder.
    compr_method_ul: bfp                                            # Uplink compression method.
    compr_bitwidth_ul: 9                                            # Uplink IQ samples bitwidth after compression.
    compr_method_dl: bfp                                            # Downlink compression method.
    compr_bitwidth_dl: 9                                            # Downlink IQ samples bitwidth after compression.
    compr_method_prach: bfp                                         # PRACH compression method.
    compr_bitwidth_prach: 9                                         # PRACH IQ samples bitwidth after compression.
    enable_ul_static_compr_hdr: false                               # Configures if the compression header is present for uplink User-Plane messages (false) or not present (true).
    enable_dl_static_compr_hdr: false                               # Configures if the compression header is present for downlink User-Plane messages (false) or not present (true).
    iq_scaling: 4.0                                                 # IQ samples scaling factor applied before compression, should be a positive value smaller than 10.
    cells:
      - network_interface: eno12409                             # Ethernet interface name used to communicate with the RU.
        ru_mac_addr: 6C:AD:AD:00:0C:5E                              # RU MAC address.
        du_mac_addr: b4:83:51:01:a5:55                              # DU MAC address.
        vlan_tag_cp: 805                                              # VLAN tag value for C-Plane.
        vlan_tag_up: 805                                              # VLAN tag value for U-Plane.
        prach_port_id: [4, 5, 6, 7]                                 # PRACH eAxC port values.
        dl_port_id: [0, 1]                                          # Downlink eAxC port values.
        ul_port_id: [0, 1, 2, 3]                                    # Uplink eAxC port values.

  cell_cfg:
    dl_arfcn: 649980 # 3749.7MHz                                               # ARFCN of the downlink carrier (center frequency). 
    band: 78                                                        # The NR band.
    channel_bandwidth_MHz: 100                                       # Bandwith in MHz. Number of PRBs will be automatically derived.
    common_scs: 30                                                  # Subcarrier spacing in kHz used for data.
    plmn: "00101"                                                   # PLMN broadcasted by the gNB.
    tac: 18                                                          # Tracking area code (needs to match the core configuration).
    pci: 136                                                          # Physical cell ID.
    nof_antennas_dl: 2                                              # Number of transmission antennas.
    nof_antennas_ul: 2                                              # Number of reception antennas.
    prach:
      prach_config_index: 159                                       # PRACH configuration index.
      prach_root_sequence_index: 1                                  # PRACH root sequence index.
      zero_correlation_zone: 0                                      # Zero correlation zone.
      prach_frequency_start: 12                                     # Offset in PRBs of lowest PRACH transmission occasion in frequency domain respective to PRB 0.
    pdsch:
      mcs_table: qam256
  #  tdd_ul_dl_cfg:
    # dl_ul_tx_period: 5
    # nof_dl_slots: 3
    # nof_dl_symbols: 9
    # nof_ul_slots: 1
    # nof_ul_symbols: 0

  log:
    filename: /tmp/gnb.log                                          # Path of the log file.
    all_level: info
  # ofh_level: warning                                                  # Logging level applied to all layers.
  # phy_level: info
  # radio_level: info
  # ofh_level: info
  # fapi_level: info
  # rlc_level: info                   # Optional TEXT (warning). Sets RLC log level.
  # pdcp_level: info                   # Optional TEXT (warning). Sets PDCP log level.
  # rrc_level: debug                    # Optional TEXT (warning). Sets RRC log level.
  # sdap_level: info                   # Optional TEXT (warning). Sets SDAP log level.
  # ngap_level: info                   # Optional TEXT (warning). Sets NGAP log level.
  # gtpu_level: info 


  pcap:
    mac_enable: false                                                # Set to true to enable MAC-layer PCAPs.
    mac_filename: /tmp/gnb_mac.pcap                                 # Path where the MAC PCAP is stored.
    ngap_enable: true                                             # Set to true to enable NGAP PCAPs.
    ngap_filename: /tmp/gnb_ngap.pcap                               # Path where the NGAP PCAP is stored.

  ru_dummy:

  amf:
    no_core: true
